server:
  port: 8085
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lifecapsule}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
security:
  jwt:
      secret-key: ${JWT_SECRET:jNVeWHuTfBMybSjIdCERIFxB3STWKAJpxZSID85M-__V65Tg3NgClGD1jLm7XdmPC8dOEqf7RtTK32IbxGbp3A}
      expiration-time: 3600000
      refresh-expiration-time: 2592000000
app:
  storage:
    root: ${APP_STORAGE_ROOT:./uploads}
  admin:
    enabled: ${APP_ADMIN_ENABLED:true}
    username: ${APP_ADMIN_USERNAME:admin}
    password: ${APP_ADMIN_PASSWORD:Admin123!}
    email: ${APP_ADMIN_EMAIL:admin@lifecapsule.local}
    first-name: ${APP_ADMIN_FIRST_NAME:Admin}
    last-name: ${APP_ADMIN_LAST_NAME:User}
